## Global processing parameters
# These parameters will be applied to all projects and libraries,
# unless overridden in the specific project or library.

parameters: &global_params
  # General settings:
  max-cpu: 8            # <INTEGER> maximum number of CPU threads to use for processing (default 1)
  mem-per-cpu: 3850     # <INTEGER> amount of memory (in MB) to allocate per CPU thread (default 3850 - for plgrid ARES cluster)
  # Reference databases for taxonomic assignment:
  reference_dbs:
      PhyloAlps: "data/ref_db/Alps_GH_clean_edit.cl.final_20-07-21.fasta"
      ArctBorBryo: "data/ref_db/arctborbryo.gh.fixed.final_20-07-21.fasta"
      EMBL143: "data/ref_db/GH_143_no-env_clean.final_20-07-21.fasta"
      PhyloNorway: "data/ref_db/Norway_GH_clean_edit.cl.final_20-07-21.fasta"
  # Merging parameters for obipairing:
  obipairing:
    gap-penalty: 2.0       # <FLOAT64>: gap penalty expressed as the multiply factor applied to the mismatch score between two nucleotides with a quality of 40 (default 2.0)
    min-identity: 0.9      # <FLOAT64> minimum identity between overlapped regions of the reads to consider the alignment (default: 0.9).
    min-overlap: 20        # <INTEGER> minimum overlap between both the reads to consider the alignment (default: 20).
    penalty-scale: 1.0     # <FLOAT64> scale factor applied to the mismatch score and the gap penalty (default 1.0).
    time: 60               # <INTEGER> maximum time (in minutes) to spend trying to merge a read pair (default 60).
  # Demultiplexing parameters:
  obimultiplex:
    matching: strict
    primer_mismatches: 2
    indels: false
    time: 60               # <INTEGER> maximum time (in minutes) to spend trying to demultiplex a library (default 60).
  # Dereplication parameters:
  obiuniq:
    time: 60               # <INTEGER> maximum time (in minutes) to spend trying to dereplicate sequences (default 60).
  # Minimum count filtering:
  filtering:
    min-count: 2           # <INTEGER> minimum count to keep a sequence (default 2)
    min-length: 10         # <INTEGER> minimum length to keep a sequence (default 10)
    time: 60              # <INTEGER> maximum time (in minutes) to spend trying to filter sequences (default 60). 
  # Filtering parameters for obiclean:
  obiclean:
    ratio: 0.05            # <FLOAT64> ratio to consider a sequence as an error of another sequence (default 0.05).
    distance: 1            # <INTEGER> maximum distance to consider two sequences as related (default 1).
    detect_chimera: false  # <BOOLEAN> if true, dereplicate sequences before filtering (default false).
    time: 60               # <INTEGER> maximum time (in minutes) to spend trying to clean sequences (default 60).
  # Taxonomic assignment parameters for obitag:
  obitag:
    time: 60               # <INTEGER> maximum time (in minutes) to spend trying to classify a sequence (default 60).
  # Post-classification table processing parameters:
  process_motu:
    time: 240              # <INTEGER> maximum time (in minutes) for process_motu.R (default 240).
  cluster_taxa:
    time: 120              # <INTEGER> maximum time (in minutes) for cluster_taxa.R (default 120).
  # final filters on OTU tables to flag low-abundance and low-replicability sequences:
  seq_filters:
    reads_within: 3        # <INTEGER> minimum number of reads within a sample to keep an OTU (default 3)
    reads_across: 10       # <INTEGER> minimum number of reads across all samples to keep an OTU (default 10)
    reads_replicates: 3    # <INTEGER> minimum number of replicates to keep an OTU (default 3)
  # final filters for taxonomic assignments to remove low confidence assignments:
  tax_filters:
    min_identity: 1     # <FLOAT64> minimum identity to keep a sequence assignment (default 1.0)

## Projects configuration
# Each project can have multiple reference databases and multiple libraries.

projects:
  p6_loop:
    libraries:
      ZSSG3_MET1:
        forward: "/Users/ibpan/sedaDNA/ZSG3_MET1_EKDL250005403-1A_232LC3LT3_L3_1.fq.gz"
        reverse: "/Users/ibpan/sedaDNA/ZSG3_MET1_EKDL250005403-1A_232LC3LT3_L3_2.fq.gz"
        barcode_file: "/Users/ibpan/sedaDNA/barcodes-ZSG3_MET1.txt"
      ZSSG3_MET5:
        forward: "/Users/ibpan/sedaDNA/ZSG3_MET5_EKDL250005407-1A_232LC3LT3_L3_1.fq.gz"
        reverse: "/Users/ibpan/sedaDNA/ZSG3_MET5_EKDL250005407-1A_232LC3LT3_L3_2.fq.gz"
        barcode_file: "/Users/ibpan/sedaDNA/barcodes-ZSG3_MET5.txt"
    parameters:
        <<: *global_params # inherit global parameters
  
#  coi-mammals:
#    libraries:
#      ZSSG3_COI1:
#        forward: "/Users/ibpan/sedaDNA/ZSG3_COI1_EKDL250005401-1A_232LC3LT3_L3_1.fq.gz"
#        reverse: "/Users/ibpan/sedaDNA/ZSG3_COI1_EKDL250005401-1A_232LC3LT3_L3_2.fq.gz"
#        barcode_file: "/Users/ibpan/sedaDNA/barcodes-ZSG3_COI1.txt"
#      ZSSG3_COI5:
#        forward: "/Users/ibpan/sedaDNA/ZSG3_COI5_EKDL250005405-1A_232LC3LT3_L3_1.fq.gz"
#        reverse: "/Users/ibpan/sedaDNA/ZSG3_COI5_EKDL250005405-1A_232LC3LT3_L3_2.fq.gz"
#        barcode_file: "/Users/ibpan/sedaDNA/barcodes-ZSG3_COI5.txt"
#    parameters:
#        <<: *global_params # inherit global parameters
#        reference_dbs:
#          Mammal16s: "data/mammal16s-combined_uniq_id_familyfixed_len_FINAL.fasta"


