# Example Multi-Project Configuration
# Copy this file to projects.yaml and customize for your projects

mode: "multi"  # Set to "multi" to enable batch processing

global:
  # Reference databases shared across all projects
  reference_dbs:
    PhyloAlps: "data/ref_db/Alps_GH_clean_edit.cl.final_20-07-21.fasta"
    ArctBorBryo: "data/ref_db/arctborbryo.gh.fixed.final_20-07-21.fasta"
    EMBL143: "data/ref_db/GH_143_no-env_clean.final_20-07-21.fasta"
    PhyloNorway: "data/ref_db/Norway_GH_clean_edit.cl.final_20-07-21.fasta"

  # Shared processing parameters (defaults for all projects)
  parameters:
    max-cpu: 8
    obipairing:
      gap-penalty: 2.0
      min-identity: 0.9
      min-overlap: 20
      penalty-scale: 1.0
    filtering:
      min-count: 2
      min-length: 10
    obiclean:
      ratio: 0.05
      distance: 1
      detect_chimera: false
    seq_filters:
      reads_within: 3
      reads_across: 10
      reads_replicates: 3
    tax_filters:
      min_identity: 1.0
      db_prefix: "PhyloAlps"
    plotting:
      top_n_taxa: 200
      width: 10
      height: 15

  # Barcode settings
  barcodes:
    matching: strict
    primer_mismatches: 2
    indels: false

# Define your projects here
projects:
  # Example Project 1
  SiteA_2023:
    libraries:
      SiteA_MET1:
        forward: "/path/to/SiteA_MET1_R1.fq.gz"
        reverse: "/path/to/SiteA_MET1_R2.fq.gz"
        barcode_file: "/path/to/barcodes-SiteA_MET1.txt"
      SiteA_MET2:
        forward: "/path/to/SiteA_MET2_R1.fq.gz"
        reverse: "/path/to/SiteA_MET2_R2.fq.gz"
        barcode_file: "/path/to/barcodes-SiteA_MET2.txt"

  # Example Project 2 with custom parameters
  SiteB_2023:
    libraries:
      SiteB_MET1:
        forward: "/path/to/SiteB_MET1_R1.fq.gz"
        reverse: "/path/to/SiteB_MET1_R2.fq.gz"
        barcode_file: "/path/to/barcodes-SiteB_MET1.txt"

    # Override global parameters for this project
    parameters:
      seq_filters:
        reads_within: 5        # More stringent for this project
        reads_across: 15
        reads_replicates: 2

  # Example Project 3
  SiteC_2024:
    libraries:
      SiteC_MET1:
        forward: "/path/to/SiteC_MET1_R1.fq.gz"
        reverse: "/path/to/SiteC_MET1_R2.fq.gz"
        barcode_file: "/path/to/barcodes-SiteC_MET1.txt"

# Meta-analysis settings (cross-project comparisons)
meta_analysis:
  enabled: true

  # Which comparative analyses to perform
  comparisons:
    combined_heatmap: true      # Combined heatmap across all projects
    diversity_metrics: true     # Alpha/beta diversity comparison
    contamination_report: true  # Cross-project contamination summary
    taxa_overlap: true          # Venn diagram of shared taxa

  # Filtering thresholds for meta-analysis
  filters:
    min_projects: 1             # Minimum projects a taxon must appear in
    min_total_reads: 50         # Minimum total reads across all projects
    min_identity: 0.95          # Identity threshold for inclusion

  # Visualization settings for meta-analysis
  plotting:
    color_scheme: "Set2"        # RColorBrewer palette (Set1, Set2, Set3, Paired, etc.)
    width: 15                   # Plot width in inches
    height: 20                  # Plot height in inches
    cluster_projects: true      # Hierarchical clustering of projects
    cluster_taxa: true          # Hierarchical clustering of taxa
