# Multi-Project Batch Configuration
# This file enables processing multiple projects simultaneously
# and generating comparative analysis across projects

# Mode: "single" or "multi"
# - single: Use config/config.yaml (default behavior)
# - multi: Process all projects listed below
mode: "single"

# Global settings shared across all projects
global:
  # Reference databases shared across projects
  reference_dbs:
    PhyloAlps: "data/ref_db/Alps_GH_clean_edit.cl.final_20-07-21.fasta"
    ArctBorBryo: "data/ref_db/arctborbryo.gh.fixed.final_20-07-21.fasta"
    EMBL143: "data/ref_db/GH_143_no-env_clean.final_20-07-21.fasta"
    PhyloNorway: "data/ref_db/Norway_GH_clean_edit.cl.final_20-07-21.fasta"

  # Shared processing parameters
  parameters:
    max-cpu: 8
    obipairing:
      gap-penalty: 2.0
      min-identity: 0.9
      min-overlap: 20
      penalty-scale: 1.0
    filtering:
      min-count: 2
      min-length: 10
    obiclean:
      ratio: 0.05
      distance: 1
      detect_chimera: false
    seq_filters:
      reads_within: 3
      reads_across: 10
      reads_replicates: 3
    tax_filters:
      min_identity: 1.0
      db_prefix: "PhyloAlps"
    plotting:
      top_n_taxa: 200
      width: 10
      height: 15

  # Barcode settings
  barcodes:
    matching: strict
    primer_mismatches: 2
    indels: false

# List of projects to process
projects:
  ZSG3:
    # Project-specific libraries
    libraries:
      ZSSG3_MET1:
        forward: "/Users/ibpan/sedaDNA/ZSG3_MET1_EKDL250005403-1A_232LC3LT3_L3_1.fq.gz"
        reverse: "/Users/ibpan/sedaDNA/ZSG3_MET1_EKDL250005403-1A_232LC3LT3_L3_2.fq.gz"
        barcode_file: "/Users/ibpan/sedaDNA/barcodes-ZSG3_MET1.txt"
      ZSSG3_MET5:
        forward: "/Users/ibpan/sedaDNA/ZSG3_MET5_EKDL250005407-1A_232LC3LT3_L3_1.fq.gz"
        reverse: "/Users/ibpan/sedaDNA/ZSG3_MET5_EKDL250005407-1A_232LC3LT3_L3_2.fq.gz"
        barcode_file: "/Users/ibpan/sedaDNA/barcodes-ZSG3_MET5.txt"

    # Project-specific parameter overrides (optional)
    parameters:
      seq_filters:
        reads_within: 3
        reads_across: 10
        reads_replicates: 3

  # Example: Add additional projects below
  # PROJECT2:
  #   libraries:
  #     PROJECT2_LIB1:
  #       forward: "path/to/forward.fq.gz"
  #       reverse: "path/to/reverse.fq.gz"
  #       barcode_file: "path/to/barcodes.txt"
  #   parameters:
  #     seq_filters:
  #       reads_within: 5
  #       reads_across: 15
  #       reads_replicates: 2

# Meta-analysis settings (cross-project comparisons)
meta_analysis:
  enabled: true

  # Comparative visualizations
  comparisons:
    # Generate combined heatmap across all projects
    combined_heatmap: true

    # Generate diversity metrics comparison
    diversity_metrics: true

    # Generate cross-project contamination report
    contamination_report: true

    # Venn diagram of shared taxa
    taxa_overlap: true

  # Filtering for meta-analysis
  filters:
    # Minimum number of projects a taxon must appear in
    min_projects: 1

    # Minimum total reads across all projects
    min_total_reads: 50

    # Identity threshold for inclusion
    min_identity: 0.95

  # Visualization settings
  plotting:
    color_scheme: "Set2"  # RColorBrewer palette
    width: 15
    height: 20
    cluster_projects: true  # Hierarchical clustering of projects
    cluster_taxa: true
